name: Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20

    - name: Get dependency
      run: go mod tidy

    - name: Test
      run: go test -v -coverprofile=coverage.txt -covermode=atomic ./...

    - name: coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unit-tests
        fail_ci_if_error: false # optional (default = false)
        verbose: false # optional (default = false)

